### ISSUE TITLE
[Common] Dynamic Id tekshiradigan attribut kerak

### ISSUE THREAD

**Issue by leverow** [ilmhub-uz/FurnitureShop#17]
![Rasm](https://user-images.githubusercontent.com/24845993/207530086-624fe840-0ec2-4011-a74f-a80533b0fee5.png)
Yuqoridagi rasmdagi kabi holatda ishlatilganida bu attribut metodni parametrlaridan `Id` so'zi qatnashgan barcha parametrlarni yig'ib olib va ularni har biriga tegishli Databazadagi table'sini topib, anashu parametrdan olingan `entityId` ni tableda bormi yo'qmi tekshirishi kerak. Agar berilgan parametrlardagi qiymatlardan dan birontasi databazada yo'q bo'lsa `notfoundexception` otishi va pastdagi metodga o'tmasligi kerak.

### G'oya, takliflar va savollar bo'lsa izohlarda qoldiring :)

**Comment by Jamoliddin0710** [comment]
Id tekshiradigan yozildi lekin categoryni type id qoganlariniki guid bo'lganini uchun 2 xil qilib qo'ydim tekshirib ko'ringchi
