### ISSUE TITLE
[Admin.Api] DtoModellarga fluentvalidationdan foydalanib validatorlar yozish kerak

### ISSUE THREAD

**Issue by leverow** [ilmhub-uz/FurnitureShop#2]
- [x] 1.CreateCategoryDto
- [x] 2.CreateOrganizationDto
- [x] 3.UpdateCategoryDto
- [x] 4.UpdateOrganizationDto
- [x] 5.UpdateProductDto

**Comment by Jamoliddin0710** [comment]
Hamma Dtoga validatorlar yozish kerakmi  yoki faqat create bilan updategami
